server:
 port: 8081
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: APIGateWayFacebook
 cloud:
  gateway:
   routes:
     - id: ProfileModule
       uri: http://localhost:8082/
       predicates:
       - Path=/api/v1/**
     - id: PostModule
       uri: http://localhost:8083/
       predicates:
       - Path=/api2/v1/**
     - id: MarketPlaceModule
       uri: http://localhost:8084/
       predicates:
       - Path=/api3/v1/**
     - id: JWTServiceModule
       uri: http://localhost:8085/
       predicates:
       - Path=/api/jwt/**
   