server:
  port: 8084
spring:
  application:
      name: MarketPlace
  data:
   mongodb:
     uri: mongodb+srv://jaswant-rawat:test@facebookservice.gzd1r.mongodb.net/facebookService
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher       
data:
  exception:
     dataExists: Record Already Exists..!!
     dataNotFound: Record Id Not Found..!!
jwt:
  secret: secretkey123
eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/
logging:
  file:
    path: MarketPlaceLogs/mplog.log


#logging.level.root=INFO
#logging.level.com.capgemini=TRACE


