server:
  port: 8082
spring:
  application:
      name: ProfileService
  data:
   mongodb:
     uri: mongodb+srv://jaswant-rawat:test@facebookservice.gzd1r.mongodb.net/facebookService
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher       
data:
  exception:
     dataExists: Record Already Exists..!!
     dataNotFound: Record Id Not Found..!!

eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/
logging:
  file:
    path: ProfileLogs/proflog.log


#logging.level.root=INFO
#logging.level.com.capgemini=TRACE


